services:
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/parse --data 'text=next tuesday' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  stt:
    build:
      context: ./backend/stt
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - MODEL_TYPE=rnnt
    volumes:
      - ./models:/models
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://stt:8003/healthcheck || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  t2v-transformers:
    build:
      context: ./backend/embedder
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      ENABLE_CUDA: 0
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
    depends_on:
      - t2v-transformers
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/v1/.well-known/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  weaviate-init:
    build:
      context: ./backend/init
      dockerfile: Dockerfile
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080
  parser:
    build:
      context: ./backend/parser
      dockerfile: Dockerfile
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - DUCKLING_URL=http://duckling:8000
    depends_on:
      weaviate:
        condition: service_started
      duckling:
        condition: service_started
    volumes:
      - ./data:/data
  app:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      weaviate:
        condition: service_started
      duckling:
        condition: service_started
      stt:
        condition: service_started
    environment:
      - GIGACHAT_AUTH_TOKEN=${GIGACHAT_AUTH_TOKEN}
      - WEAVIATE_URL=http://weaviate:8080
      - DUCKLING_URL=http://duckling:8000
      - STT_URL=http://stt:8003
  telegram-bot:
    build:
      context: ./frontend/telegram-bot
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_BASE_URL=http://app:8002
      - STT_URL=http://stt:8003
      - SALUTE_SPEECH_AUTH_TOKEN=${SALUTE_SPEECH_AUTH_TOKEN}
    volumes:
      - ./certificates:/certificates
